# generated by https://marketplace.visualstudio.com/items?itemName=danielpinto8zz6.c-cpp-project-generator
CC		:= gcc
CFLAGS	:= -g -Wall -std=c99 -pedantic -Ilib/bigint/build/include
CLIBS := -Llib/bigint/build/lib
BIN		:= bin
SRC		:= src

LIBRARIES	:= -lbigint

ifeq ($(OS),Windows_NT)
EXECUTABLE	:= njvm.exe
else
EXECUTABLE	:= njvm
endif

SOURCEDIRS	:= $(shell find $(SRC) -type d)

SOURCES		:= $(wildcard $(patsubst %,%/*.c, $(SOURCEDIRS)))
OBJECTS		:= $(SOURCES:.c=.o)

all: $(BIN)/$(EXECUTABLE)

.PHONY: clean
clean:
	-$(RM) $(BIN)/$(EXECUTABLE)
	-$(RM) $(OBJECTS)


run: all
	./$(BIN)/$(EXECUTABLE)

$(BIN)/$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $(CINCLUDES) $(CLIBS) $^ -o $@ $(LIBRARIES)